name = "字体替换为 HarmonyOS，在 Windows 下获得接近苹方的阅读体验"
description = "在不支持苹方的情况下采用和 Bilibili 一样的 HarmonyOS 字体，提升阅读体验。仅对常见根节点进行检查，不支持部分字体未声明在根节点的页面，不支持声明了 CSP 限制的页面（如 GitHub）"
version = "1.0"
match = "*://*/*"
exclude = [
  "*://*.bilibili.com/*",
  "*://*.github.com/*"
]
grant = "none"
run-at = "document-end"
