version = "1.4"
match = [
  "*://*.twitter.com/*",
  "*://*.x.com/*",
]
grant = "none"
run-at = "document-end"

[name]
default = "Twitter t.co to Direct Link Converter"
zh-CN = "推特 t.co 转直接链接"

[description]
default = "Automatically converts Twitter's indirect t.co links into direct, original URLs for a more transparent and streamlined browsing experience."
zh-CN = "把推特的 t.co 中转跳转链接改为直接跳转"
