name = "Twitter t.co to Direct Link Converter"
version = "1.2"
match = [
  "*://twitter.com/*",
  "*://x.com/*",
  "*://*.twitter.com/*",
  "*://*.x.com/*",
]
grant = "none"
run-at = "document-end"

[description]
default = "把推特的 t.co 中转跳转链接改为直接跳转"
en = "Automatically converts Twitter's indirect t.co links into direct, original URLs for a more transparent and streamlined browsing experience."
